name: "\U0001F41B Bug Report"
description: "Report a bug or problem with the code."
title: "(short issue description)"
labels: [bug, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Description
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        Tell us what should happen.
      placeholder: Expected behavior
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: |
        Tell us what happens instead of the expected behavior.
        Include full errors, uncaught exceptions, stack traces, and relevant logs.
        For more info on logging, please see [here](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html)
      placeholder: Current behavior
    validations:
        required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
        For more complex issues provide a repo with the smallest sample that reproduces the bug.
        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
      placeholder: Reproduction Steps
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug.
        If you have any ideas for a solution, feel free to describe them here. Otherwise, a solution will be linked in the comments once finished
      placeholder: Possible Solution
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world.
      placeholder: Context
    validations:
      required: false

  - type: textarea
    id: dotnet-sdk-version
    attributes:
      label: AWS .NET SDK and/or Package version used
      description: NuGet Packages used
      placeholder: AWSSDK.S3 3.7.8.13
    validations:
      required: true

  - type: input
    id: platform-used
    attributes:
      label: Targeted .NET Platform
      description: "Example: .NET Framework 4.7, .NET Core 3.1, .NET 6, etc."
      placeholder: .NET Framework 4.7, .NET Core 3.1, .NET 6, etc.
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
      description: "Example: Windows 10, OSX Mojave, Ubuntu, AmazonLinux, etc."
      placeholder: Windows 10, OSX Mojave, Ubuntu, AmazonLinux, etc.
    validations:
      required: true

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledge
      options:
        - label: I can/would-like-to implement a fix for this problem myself
          required: false
